### ISSUE TITLE
example run failed report (hamble)

### ISSUE THREAD

**Issue by jackyliu16** [jhelovuo/ros2-client#12]
I was trying to testing the ros2-client if could be using in our system(this is the first step which to makesure the program is runable), but when i trying to run the example command, it seems the ros2-client depend on RustDDS could not making connection with ROS2 Process.

Operating System: Ubuntu2204
ROS2 Version: hamble

Using both client and service from ros2-client example is receiverable, but if one of it is ROS2 (default as FastDDS) it will not receiver anykinds of information, and also the ros2 node list couldn't detect the node.

```bash
$ ros2 node list
/minimal_service
/rqt...
```

![image](https://github.com/jhelovuo/ros2-client/assets/50787361/dd9d9404-0f16-49a2-b6dc-761bfa3aa9c2)
![image](https://github.com/jhelovuo/ros2-client/assets/50787361/86036f25-5bc5-4f15-99ef-7f73864f9c24)

by the ways, example one also couldn't detect and pass all the test.

**Comment by SelimV** [comment]
Hi, this looks like what I experienced with the issue https://github.com/jhelovuo/RustDDS/issues/285 in RustDDS. You can try running the branch [ros2-client/rustdds_error_renewal](https://github.com/jhelovuo/ros2-client/tree/rustdds_error_renewal), which should be compatible with [RustDDS/master](https://github.com/jhelovuo/RustDDS/tree/master). As no new release of RustDDS has been made, you will need to provide the up-to-date version, see line 18 at [Cargo.toml](https://github.com/jhelovuo/ros2-client/blob/rustdds_error_renewal/Cargo.toml).

**Comment by jackyliu16** [comment]
It seems ros2-client(rustdds_error_renewal) and RustDDS(master) compatible not work for me, it's still the same problem (

**Comment by SelimV** [comment]
The new releases of RustDDS and ros2-client should fix the issue I mentioned. Please reopen if the problem persists.
