### ISSUE TITLE
Clean up turtlesim_teleop example

### ISSUE THREAD

**Issue by jhelovuo** [jhelovuo/ros2-client#3]
Some parts are unnecessarily complex.

Operation is not smooth.

Responses should be properly printed on screen.

**Comment by tylerjw** [comment]
I'm trying to experiment with this with ros 2 rolling and it doesn't seem to show up as a node in the node list and nothing connects. I'm unsure how to debug.

**Comment by jhelovuo** [comment]
Issue died due to old age.
