### ISSUE TITLE
Error structs no longer implement `std` error traits

### ISSUE THREAD

**Issue by alexveecle** [jhelovuo/ros2-client#30]
Hi,

We were using ros2-client 0.6.1 and we decided to update. We realized that:

https://github.com/jhelovuo/ros2-client/blob/master/src/node.rs#L558
https://github.com/jhelovuo/ros2-client/blob/master/src/names.rs#L99

, do not implement error traits anymore, so we cannot, for example, use `?` to propagate them using anyhow. 0.6.1 did this, so we're wondering if this has been some kind of accident.

Cheers,

Álex

**Comment by jhelovuo** [comment]
Thanks for pointing this out. That change was an accident.

It should be fixed now in release 0.7.4.
