### ISSUE TITLE
Publisher has hard time finding subscribers

### ISSUE THREAD

**Issue by nime88** [jhelovuo/ros2-client#33]
When using `ros2 topic int /some_topic` and `ros2 topic echo /some_topic` ros2_client doesn't necessarily find any subscribers with `get_subscription_count` or `wait_for_subscription`. I used the orignal node.

**Comment by jhelovuo** [comment]
This was s bug in the new implementation of Send Futures returned by `wait_for_subscription` and `wait_for_publisher`.
They tended to get stuck due to improper handling of Futures. This is now fixed in release 0.7.5.
